sudo: true
dist: bionic
os: linux
language: bash
services:
  - docker
branches:
  only:
  - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed. Version tags should be of the form: v0.1.0
  - /^v\d+\.\d+\.\d+.*$/
before_install:
  - sed -i 's/#INSERT_HERE/COPY . \/mod_event_kafka/g' .devcontainer/Dockerfile
  - cat .devcontainer/Dockerfile
  - docker build -t mod_event_kafka -f .devcontainer/Dockerfile .
  - docker run mod_event_kafka make -C /mod_event_kafka
script:
  -  docker run -i mod_event_kafka bash -c "cd /mod_event_kafka && make && ls"
